/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGUI;

import ejer5.utils.UtilidadesGrafica;
import gestora.GestorCoches;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Coche;
import modelo.MyException;

/**
 *
 * @author AluDAM
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
        initComponents();
        metodoQueTengoQueBorrar();
        pongoImagen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void metodoQueTengoQueBorrar() {

        try {
            gestora.GestorCoches.addCoche(new Coche("Seat", 10000));
            gestora.GestorCoches.addCoche(new Coche("Opel", 60000));
            gestora.GestorCoches.addCoche(new Coche("Pepe", 630000));
            gestora.GestorCoches.addCoche(new Coche("Lole", 670000));
            gestora.GestorCoches.addCoche(new Coche("Tesla", 40000));
            System.out.println(gestora.GestorCoches.cochesFeos());
        } catch (MyException ex) {
            muestroError("Malos coches....");
        }
    }

    private void muestroError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "CPIFP", JOptionPane.ERROR_MESSAGE);
    }

    private String pideCadena(String mensaje) {
        return UtilidadesGrafica.pideCadena(mensaje);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        etiTitulo = new javax.swing.JLabel();
        botonFin = new javax.swing.JButton();
        botonAlta1 = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonVendidos = new javax.swing.JButton();
        botonGangas = new javax.swing.JButton();
        botonVender = new javax.swing.JButton();
        botonEnVenta = new javax.swing.JButton();
        botonCambiarIVA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONCHIIII");

        etiTitulo.setFont(new java.awt.Font("Ebrima", 0, 36)); // NOI18N
        etiTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiTitulo.setText("CONCESIONARIO");

        botonFin.setText("FIN");
        botonFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinActionPerformed(evt);
            }
        });

        botonAlta1.setText("ALTA");
        botonAlta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlta1ActionPerformed(evt);
            }
        });

        botonModificar.setText("MODIFICAR");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonVendidos.setText("VENDIDOS");
        botonVendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVendidosActionPerformed(evt);
            }
        });

        botonGangas.setText("GANGAS");
        botonGangas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGangasActionPerformed(evt);
            }
        });

        botonVender.setText("VENDER");
        botonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVenderActionPerformed(evt);
            }
        });

        botonEnVenta.setText("EN VENTA");
        botonEnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnVentaActionPerformed(evt);
            }
        });

        botonCambiarIVA.setText("CAMBIAR IVA");
        botonCambiarIVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarIVAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonAlta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(botonVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonEnVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(162, 162, 162)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGangas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCambiarIVA, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(26, 26, 26))
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(etiTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(etiTitulo)
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonGangas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAlta1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCambiarIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonFin, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinActionPerformed
        // TODO add your handling code here:
        fin();
    }//GEN-LAST:event_botonFinActionPerformed

    private void botonAlta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlta1ActionPerformed
        VentanaAltaCoche vA = new VentanaAltaCoche(this);
        vA.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_botonAlta1ActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        VentanaModificacion vM = new VentanaModificacion(this);
        vM.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVenderActionPerformed
        VentanaVender vV = new VentanaVender(this);
        vV.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVenderActionPerformed

    private void botonEnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnVentaActionPerformed
        VentanaEnVenta vE = new VentanaEnVenta(this);
        vE.setVisible(true);
        vE.setAlwaysOnTop(true);
        this.setVisible(false);

    }//GEN-LAST:event_botonEnVentaActionPerformed

    private void botonVendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVendidosActionPerformed
        VentanaVendidos vVe = new VentanaVendidos(this);
        vVe.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonVendidosActionPerformed

    private void botonGangasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGangasActionPerformed
        VentanaGangas vG = new VentanaGangas(this);
        vG.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonGangasActionPerformed

    private void botonCambiarIVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarIVAActionPerformed
        String iva = pideCadena("Escribe el nuevo IVA: ");
        float ivaBien = 0;
        try {
            ivaBien = Float.parseFloat(iva);
        }catch(NumberFormatException | NullPointerException ex){
            UtilidadesGrafica.muestraError("IVA incorrecto. ");
        }
        Coche.setIVA(ivaBien);


    }//GEN-LAST:event_botonCambiarIVAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    private void fin() {
        //Somos ordenados y limpiamos todo. 
        System.exit(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlta1;
    private javax.swing.JButton botonCambiarIVA;
    private javax.swing.JButton botonEnVenta;
    private javax.swing.JButton botonFin;
    private javax.swing.JButton botonGangas;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonVender;
    private javax.swing.JButton botonVendidos;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.JPanel fondo;
    // End of variables declaration//GEN-END:variables

    private void pongoImagen() {
        //Cerar el objeto imagen:
        ImageIcon miAudi = new ImageIcon("imagenes\\miAudi.png");
        ImageIcon logo = new ImageIcon("imagenes\\miAudi.png");

        this.setIconImage(logo.getImage());

    }
}
