/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGUI;

import javax.swing.JOptionPane;
import modelo.Coche;
import modelo.CocheImportado;
import modelo.CocheKmCero;
import modelo.MyException;

/**
 *
 * @author AluDAM
 */
public class VentanaAltaCoche extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAltaCoche
     */
    private Coche c; //Coche falso para probetear. 
    private CocheKmCero k; //Coche falso para probetear. 
    private CocheImportado i; //Coche falso para probetear. 
    private VentanaMenu vM;

    public VentanaAltaCoche(VentanaMenu vM) {
        c = new Coche();
        this.vM = vM;
        initComponents();
        textCodigo.setEnabled(false);
        limpioFormulario();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        etiTitulo = new javax.swing.JLabel();
        etiCodigo = new javax.swing.JLabel();
        etiModelo = new javax.swing.JLabel();
        etiPrecio = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        textModelo = new javax.swing.JTextField();
        textPrecio = new javax.swing.JTextField();
        botonAlta = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        etiImpuestoHomologacion = new javax.swing.JLabel();
        textImpuestoHomologacion = new javax.swing.JTextField();
        etiKilometros = new javax.swing.JLabel();
        textKilometros = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LOS ENLACES --- ALTA COCHE");

        etiTitulo.setFont(new java.awt.Font("Edwardian Script ITC", 0, 36)); // NOI18N
        etiTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiTitulo.setText("Concesionario Conchi");

        etiCodigo.setText("CÓDIGO");

        etiModelo.setText("MODELO");

        etiPrecio.setText("PRECIO");

        textCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoActionPerformed(evt);
            }
        });

        textModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textModeloActionPerformed(evt);
            }
        });

        botonAlta.setText("ALTA");
        botonAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAltaActionPerformed(evt);
            }
        });

        botonBorrar.setText("BORRAR");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonVolver.setText("VOLVER");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        etiImpuestoHomologacion.setText("IMPUESTO HOMOLOGACION");

        textImpuestoHomologacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textImpuestoHomologacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textImpuestoHomologacionFocusLost(evt);
            }
        });
        textImpuestoHomologacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textImpuestoHomologacionMouseClicked(evt);
            }
        });
        textImpuestoHomologacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textImpuestoHomologacionActionPerformed(evt);
            }
        });

        etiKilometros.setText("KILOMETROS");

        textKilometros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textKilometrosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textKilometrosFocusLost(evt);
            }
        });
        textKilometros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textKilometrosMouseClicked(evt);
            }
        });
        textKilometros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKilometrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(etiTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(botonAlta)
                        .addGap(69, 69, 69)
                        .addComponent(botonBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(botonVolver))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(etiPrecio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiImpuestoHomologacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                .addComponent(etiKilometros, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(textModelo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textImpuestoHomologacion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textKilometros, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(112, 112, 112))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(etiTitulo)
                .addGap(30, 30, 30)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiCodigo)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiModelo)
                    .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiPrecio)
                    .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiImpuestoHomologacion)
                            .addComponent(textImpuestoHomologacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textKilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(etiKilometros)))
                .addGap(18, 18, 18)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAlta)
                    .addComponent(botonBorrar)
                    .addComponent(botonVolver))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoActionPerformed
        try {
            c.setModelo(textModelo.getText());
        } catch (MyException ex) {
            muestroError(ex.getMessage());
        }
    }//GEN-LAST:event_textCodigoActionPerformed
    private void muestroError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "CPIFP", JOptionPane.ERROR_MESSAGE);
    }

    private void botonAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAltaActionPerformed
        try {
            Coche coche;
            if (textKilometros.getText().isEmpty()
                    && textImpuestoHomologacion.getText().isEmpty()) {
                coche = new Coche(textModelo.getText(),
                        textPrecio.getText());
            } else if (!textImpuestoHomologacion.getText().isEmpty()) {
                coche = new CocheImportado(textImpuestoHomologacion.getText(),
                        textModelo.getText(),
                        textPrecio.getText());
            } else {
                coche = new CocheKmCero(
                        textKilometros.getText(), 
                        textModelo.getText(), 
                        textPrecio.getText());
            }

            if (gestora.GestorCoches.addCoche(coche)) {
                JOptionPane.showMessageDialog(this,
                        "Alta correcta");
                limpioFormulario();
            } else {
                muestroError("Problemas en la colección...");
            }
        } catch (MyException ex) {
            muestroError(ex.getMessage());
        }

    }//GEN-LAST:event_botonAltaActionPerformed

    private void limpioFormulario() {
        c = new Coche();
        textCodigo.setText(c.getCodigo());
        textModelo.setText("");
        textPrecio.setText("");
        textModelo.requestFocus();
        textKilometros.setText("");
        textImpuestoHomologacion.setText("");
    }

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        limpioFormulario();
    }//GEN-LAST:event_botonBorrarActionPerformed
    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
        vM.setVisible(true);
    }//GEN-LAST:event_botonVolverActionPerformed
    private void textModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textModeloActionPerformed

    private void textImpuestoHomologacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textImpuestoHomologacionActionPerformed
        desactivaKilometros();
    }//GEN-LAST:event_textImpuestoHomologacionActionPerformed

    private void textKilometrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKilometrosActionPerformed
        desactivaImpuesto();
    }//GEN-LAST:event_textKilometrosActionPerformed

    private void textKilometrosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textKilometrosFocusLost
        //desactivaImpuesto();
    }//GEN-LAST:event_textKilometrosFocusLost


    private void textImpuestoHomologacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textImpuestoHomologacionFocusLost
        //desactivaKilometros();
    }//GEN-LAST:event_textImpuestoHomologacionFocusLost

    private void desactivaImpuesto() {
        textImpuestoHomologacion.setEnabled(false);
        textKilometros.setEnabled(true);
        textKilometros.requestFocus();
        textImpuestoHomologacion.setText("");
    }

    private void desactivaKilometros() {
        textKilometros.setEnabled(false);
        textImpuestoHomologacion.setEnabled(true);
        textImpuestoHomologacion.requestFocus();
        textKilometros.setText("");
    }

    private void textImpuestoHomologacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textImpuestoHomologacionFocusGained
        desactivaKilometros();
    }//GEN-LAST:event_textImpuestoHomologacionFocusGained

    private void textKilometrosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textKilometrosFocusGained
        desactivaImpuesto();
    }//GEN-LAST:event_textKilometrosFocusGained

    private void textKilometrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textKilometrosMouseClicked
        desactivaImpuesto();
    }//GEN-LAST:event_textKilometrosMouseClicked

    private void textImpuestoHomologacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textImpuestoHomologacionMouseClicked
        desactivaKilometros();
    }//GEN-LAST:event_textImpuestoHomologacionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAlta;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel etiCodigo;
    private javax.swing.JLabel etiImpuestoHomologacion;
    private javax.swing.JLabel etiKilometros;
    private javax.swing.JLabel etiModelo;
    private javax.swing.JLabel etiPrecio;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.JPanel fondo;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textImpuestoHomologacion;
    private javax.swing.JTextField textKilometros;
    private javax.swing.JTextField textModelo;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables
}
