/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGUI;

import javax.swing.JOptionPane;
import modelo.Coche;
import modelo.CocheImportado;
import modelo.CocheKmCero;
import modelo.MyException;

/**
 *
 * @author AluDAM
 */
public class VentanaVender extends javax.swing.JFrame {

    private Coche coche;
    private CocheImportado i;
    private CocheKmCero k;
    private VentanaMenu vM;

    /**
     * Vender un coche: abrirá un formulario nuevo que pedirá el código del
     * coche, si no existe se mostrará el mensaje de error y si existe, se
     * mostrarán sus datos, siempre que el coche esté disponible para la venta,
     * si no lo está se mostrará un mensaje de “Vendido”. Se pondrá el precio de
     * venta y el precio total a pagar, calculado según el tipo de coche que
     * sea. Habrá un botón “Vender”, cuando se pulse, se marcará el coche como
     * vendido.
     *
     * @param vM
     */
    public VentanaVender(VentanaMenu vM) {
        initComponents();
        limpioFormulario();
        this.vM = vM;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoEnVenta = new javax.swing.ButtonGroup();
        elPanel = new javax.swing.JPanel();
        etiPrecio = new javax.swing.JLabel();
        etiModelo = new javax.swing.JLabel();
        textPrecio = new javax.swing.JTextField();
        etiTitulo = new javax.swing.JLabel();
        etiCodigo = new javax.swing.JLabel();
        textCodigo = new javax.swing.JTextField();
        botonLimpiar = new javax.swing.JButton();
        botonVender = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        textModelo = new javax.swing.JTextField();
        textKmOImpor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaMuestra = new javax.swing.JTextArea();
        etiKmOImpor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiPrecio.setText("PRECIO");

        etiModelo.setText("MODELO");

        textPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrecioActionPerformed(evt);
            }
        });

        etiTitulo.setFont(new java.awt.Font("Edwardian Script ITC", 0, 36)); // NOI18N
        etiTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiTitulo.setText("Concesionario Conchi");

        etiCodigo.setText("CÓDIGO");

        textCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodigoActionPerformed(evt);
            }
        });

        botonLimpiar.setText("LIMPIAR");
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        botonVender.setText("VENDER");
        botonVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVenderActionPerformed(evt);
            }
        });

        botonVolver.setText("VOLVER");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        textKmOImpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textKmOImporActionPerformed(evt);
            }
        });

        textAreaMuestra.setColumns(20);
        textAreaMuestra.setRows(5);
        jScrollPane1.setViewportView(textAreaMuestra);

        etiKmOImpor.setText("OCULTA");

        javax.swing.GroupLayout elPanelLayout = new javax.swing.GroupLayout(elPanel);
        elPanel.setLayout(elPanelLayout);
        elPanelLayout.setHorizontalGroup(
            elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elPanelLayout.createSequentialGroup()
                .addGroup(elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(elPanelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(etiTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(elPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(elPanelLayout.createSequentialGroup()
                                .addGroup(elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiPrecio)
                                    .addComponent(etiCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiModelo)
                                    .addComponent(etiKmOImpor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textKmOImpor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, elPanelLayout.createSequentialGroup()
                                .addComponent(botonVender)
                                .addGap(18, 18, 18)
                                .addComponent(botonLimpiar)
                                .addGap(148, 148, 148)
                                .addComponent(botonVolver))
                            .addComponent(jScrollPane1))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        elPanelLayout.setVerticalGroup(
            elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(etiTitulo)
                .addGap(26, 26, 26)
                .addGroup(elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiCodigo))
                .addGap(12, 12, 12)
                .addGroup(elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(elPanelLayout.createSequentialGroup()
                        .addComponent(etiPrecio)
                        .addGap(28, 28, 28)
                        .addComponent(etiModelo)
                        .addGap(18, 18, 18)
                        .addComponent(etiKmOImpor))
                    .addGroup(elPanelLayout.createSequentialGroup()
                        .addComponent(textPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textKmOImpor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(elPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVender)
                    .addComponent(botonLimpiar)
                    .addComponent(botonVolver))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(elPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(elPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrecioActionPerformed
        try {
            coche.setPrecio(textPrecio.getText());
        } catch (MyException ex) {
            muestraError(ex.getMessage());
            textPrecio.setText(coche.getPrecio() + "");
        }

    }//GEN-LAST:event_textPrecioActionPerformed

    private void textCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodigoActionPerformed

        try {
            coche = gestora.GestorCoches.buscaCoche(textCodigo.getText());
            rellenoFormulario(coche);
        } catch (MyException | IndexOutOfBoundsException ex) {
            muestraError(ex.getMessage());
        }
        if (coche instanceof CocheImportado) {
            i = (CocheImportado) coche;
            etiKmOImpor.setVisible(true);
            etiKmOImpor.setText("IMPUESTO HOMOLOGACION");
            textKmOImpor.setText(i.getImpuestoHomologacion()+"");
        }
        if (coche instanceof CocheKmCero) {
            k = (CocheKmCero) coche;
            etiKmOImpor.setVisible(true);
            etiKmOImpor.setText("KILOMETROS");
            textKmOImpor.setText(k.getKm()+"");
        }
    }//GEN-LAST:event_textCodigoActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
        limpioFormulario();
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVenderActionPerformed
        //Error: habra codigos repetidos cuando se borre uno que no sea el ultimo.
        try {
            //Modifico el coche
            coche.setPrecio(textPrecio.getText());
            coche.setVendido(true);
            muestraMensaje("COCHE VENDIDO");
            limpioFormulario();
        } catch (MyException ex) {
            muestraError(ex.getMessage());
        }
    }//GEN-LAST:event_botonVenderActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        vM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void textKmOImporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textKmOImporActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textKmOImporActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonVender;
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel elPanel;
    private javax.swing.JLabel etiCodigo;
    private javax.swing.JLabel etiKmOImpor;
    private javax.swing.JLabel etiModelo;
    private javax.swing.JLabel etiPrecio;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.ButtonGroup grupoEnVenta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaMuestra;
    private javax.swing.JTextField textCodigo;
    private javax.swing.JTextField textKmOImpor;
    private javax.swing.JTextField textModelo;
    private javax.swing.JTextField textPrecio;
    // End of variables declaration//GEN-END:variables

    private void limpioFormulario() {
        textPrecio.setEnabled(false);
        textPrecio.setText("");
        textAreaMuestra.setEnabled(false);
        textAreaMuestra.setText("");
        textModelo.setEnabled(false);
        textModelo.setText("");
        textCodigo.setEnabled(true);
        textCodigo.setText("");
        etiKmOImpor.setVisible(false);
        etiKmOImpor.setText("");
        textKmOImpor.setEnabled(false);
        textKmOImpor.setText("");
        textCodigo.requestFocus();
        grupoEnVenta.clearSelection();
    }

    private void rellenoFormulario(Coche c) {
        if (c.isVendido()) {
            textAreaMuestra.setText("ESTA VENDIDO");
        } else {
            textCodigo.setEnabled(false);
            textPrecio.requestFocus();
            textModelo.setText(c.getModelo());
            textModelo.setEnabled(false);
            textPrecio.setText(c.getPrecio() + "");
            textPrecio.setEnabled(true);
            textAreaMuestra.setText("");
        }
    }

    private void muestraMensaje(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje,
                "CPIFP", JOptionPane.INFORMATION_MESSAGE);
    }

    private void muestraError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje,
                "CPIFP", JOptionPane.ERROR_MESSAGE);
    }
}
